### PR TITLE
Fixes #624 Checks max_coverage_drop on failed tests

### LINKED ISSUE #624: Failing tests can cause coverage drop when refusing coverage drop
Currently simplecov only checks ```maximum_coverage_drop``` on a successful test run, so a failing test run can write to ```.last_run.json``` with a lower coverage percenage than before.

Here is a scenario:

test coverage is at 100%
configure simplecov to refuse coverage drop, or set max coverage drop to 0
run specs
```.last_run.json``` shows 100%
write some new code
write a spec that only partially covers the new code that fails
run specs
```.last_run.json``` now shows < 100%
fix spec to pass, but test coverage still less that 100%
run specs
```.last_run.json``` still shows < 100%

I have PR that I will raise shortly that fixes this

### PR DESCRIPTION
**Pull request by thomas07vt**
Fixes #624 

Just taking out the max coverage drop check outside the success if statement. I can't think of a reason to leave it in the success if statement, but of course I am not too familiar with this codebase :) . Can you think of a reason why we would want to write to ```.last_run.json``` on failing tests?

The only thing that I wasn't sure of is, if a test is failing, maybe we want to leave the pre-existing non-zero exit status rather than writing an exit status of 3.

### CODE REVIEW

**Comment by PragTob** [comment]
Hi, first thanks for your contribution! I'll take a look, but first it seems that the build is failing because rubocop inspects some vendored gems... grml.

**Comment by thomas07vt** [comment]
Yeah I checked the ```.rubocop.yml``` file and its using an exclude path that seems like it should work ```'vendor/bundle/**/*'``` so I am not sure what's going on...

**Comment by PragTob** [comment]
and that failure is a bug in rubocop... PRing then workaround fixing. Then reviewing here hopefully :)

**Comment by thomas07vt** [comment]
Oh, you have already done that!... closing this one :)

**Comment by PragTob** [comment]
Nope, this one we sitll need

**Comment by thomas07vt** [comment]
> I understand the bug correctly this should also solve it, right? :)

yeah that should work too. I can update my PR to add that change.

**Comment by PragTob** [comment]
That'd be great!

**Comment by thomas07vt** [comment]
@PragTob would you prefer the duplicate ```write``` call as I have it in the PR, or a duplicate check on ```@exit_status`` like this:

```ruby
    if @exit_status == SimpleCov::ExitCodes::SUCCESS # No other errors
      if covered_percent < SimpleCov.minimum_coverage # rubocop:disable Metrics/BlockNesting
        $stderr.printf("Coverage (%.2f%%) is below the expected minimum coverage (%.2f%%).\n", covered_percent, SimpleCov.minimum_coverage)
        @exit_status = SimpleCov::ExitCodes::MINIMUM_COVERAGE
      elsif covered_percentages.any? { |p| p < SimpleCov.minimum_coverage_by_file } # rubocop:disable Metrics/BlockNesting
        $stderr.printf("File (%s) is only (%.2f%%) covered. This is below the expected minimum coverage per file of (%.2f%%).\n", SimpleCov.result.least_covered_file, covered_percentages.min, SimpleCov.minimum_coverage_by_file)
        @exit_status = SimpleCov::ExitCodes::MINIMUM_COVERAGE
      elsif (last_run = SimpleCov::LastRun.read) # rubocop:disable Metrics/BlockNesting
        coverage_diff = last_run["result"]["covered_percent"] - covered_percent
        if coverage_diff > SimpleCov.maximum_coverage_drop # rubocop:disable Metrics/BlockNesting
          $stderr.printf("Coverage has dropped by %.2f%% since the last time (maximum allowed: %.2f%%).\n", coverage_diff, SimpleCov.maximum_coverage_drop)
          @exit_status = SimpleCov::ExitCodes::MAXIMUM_COVERAGE_DROP
        end
      end
    end

    if @exit_status == SimpleCov::ExitCodes::SUCCESS
      SimpleCov::LastRun.write(:result => {:covered_percent => covered_percent})
    end
```

I kinda like the duplicate ```@exit_status``` check better, but I'll defer to you :)

File: lib/simplecov/defaults.rb [hunk 1]
```diff
@@ -83,14 +83,13 @@
         if coverage_diff > SimpleCov.maximum_coverage_drop # rubocop:disable Metrics/BlockNesting
           $stderr.printf("Coverage has dropped by %.2f%% since the last time (maximum allowed: %.2f%%).\n", coverage_diff, SimpleCov.maximum_coverage_drop)
           @exit_status = SimpleCov::ExitCodes::MAXIMUM_COVERAGE_DROP
+        else
+          SimpleCov::LastRun.write(:result => {:covered_percent => covered_percent})
         end
+      else
+        SimpleCov::LastRun.write(:result => {:covered_percent => covered_percent})
```
Comment (PragTob) [inline lib/simplecov/defaults.rb]: I think I'd just move the write tot he bottom of the bigger if and keep the `exit_status` check as before I think. But this whole code is ripe for some proper refactoring though :)

**Comment by thomas07vt** [comment]
@PragTob How about this?

**Comment by PragTob** [comment]
Should be good enough, thanks! :)
